name: Update Prayer Times

on:
  schedule:
    - cron: '0 5 * * 0'  # Every Sunday at 5AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Critical for push access
      pull-requests: write  # Optional for future PR capabilities

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper git history
          persist-credentials: true  # Ensures git push works

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Pinned version for stability
          cache: 'pip'  # Caches dependencies for faster runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: |
          mkdir -p docs  # Ensure docs directory exists
          python fetch_and_format_prayer_times.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/prayer_times.json
          
          # Better commit message with date
          COMMIT_DATE=$(date +'%Y-%m-%d')
          git commit -m "📅 Automated prayer times update ($COMMIT_DATE) [skip ci]" || exit 0
          
          # Robust push command
          git pull --rebase origin main
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
