name: Prayer Times API Updater

on:
  schedule:
    - cron: '0 5 * * 0'  # Weekly update
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update data
        run: |
          pip install requests
          python fetch_and_format_prayer_times.py
          
      - name: Push changes
        run: |
          git config --global user.name "iOS-App-Updater"
          git config --global user.email "actions@users.noreply.github.com"
          git add docs/prayer_times.json
          git commit -m "📅 Auto-update prayer data"
          git push
